name: salesforce_analytics

profile: salesforce_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  salesforce_analytics:
    +schema: raw

models:
  salesforce_analytics:
    staging:
      +materialized: view
      +schema: staging_salesforce
    marts:
      sales:
        +materialized: table
        +schema: marts_sales
      marketing:
        +materialized: table
        +schema: marts_marketing
      customer:
        +materialized: table
        +schema: marts_customer
      dimensions:
        +materialized: table
        +schema: marts_dimensions
        metricflow_time_spine:
          +materialized: view

snapshots:
  salesforce_analytics:
    +schema: snapshots_salesforce
